export enum ENV {
  DATABASE_URL = "DATABASE_URL",
  DIRECT_URL = "DIRECT_URL",
  DIRECT_CLIENT_API_KEY = "DIRECT_CLIENT_API_KEY",
  NUBAPI_API_KEY = "NUBAPI_API_KEY",
  JWT_SECRET_KEY = "JWT_SECRET_KEY",
  CLIENT_URL = "CLIENT_URL",
  SERVER_URL = "SERVER_URL",
  NODE_ENV = "NODE_ENV",
  PORT = "PORT",
  PAYSTACK_PUBLIC_KEY = "PAYSTACK_PUBLIC_KEY",
  PAYSTACK_SECRET_KEY = "PAYSTACK_SECRET_KEY",
  SOLFLARE_WALLET_PUBLIC_KEY = "SOLFLARE_WALLET_PUBLIC_KEY",
}
